query myQuery($id: String! $locale: String) {
  menu(id: $id, locale: $locale) {
    name
    slug
    itemsCollection {
      items {
        sys {
          id
        }
        __typename
      }
    }
    __typename
  }
}
